In [ ]:
import pandas as pd

filename = 'Postures.csv'
data = pd.read_csv(filename)

print(data.shape)
print(data.columns)
data.head(10)

(78096, 38)
Index(['Class', 'User', 'X0', 'Y0', 'Z0', 'X1', 'Y1', 'Z1', 'X2', 'Y2', 'Z2',
       'X3', 'Y3', 'Z3', 'X4', 'Y4', 'Z4', 'X5', 'Y5', 'Z5', 'X6', 'Y6', 'Z6',
       'X7', 'Y7', 'Z7', 'X8', 'Y8', 'Z8', 'X9', 'Y9', 'Z9', 'X10', 'Y10',
       'Z10', 'X11', 'Y11', 'Z11'],
      dtype='object')

   Class  User         X0         Y0         Z0  ...  Y10  Z10  X11  Y11  Z11
0      0     0   0.000000   0.000000   0.000000  ...    0    0    0    0    0
1      1     0  54.263880  71.466776 -64.807709  ...    ?    ?    ?    ?    ?
2      1     0  56.527558  72.266609 -61.935252  ...    ?    ?    ?    ?    ?
3      1     0  55.849928  72.469064 -62.562788  ...    ?    ?    ?    ?    ?
4      1     0  55.329647  71.707275 -63.688956  ...    ?    ?    ?    ?    ?
5      1     0  55.142401  71.435607 -64.177303  ...    ?    ?    ?    ?    ?
6      1     0  55.581184  71.641201 -63.703137  ...    ?    ?    ?    ?    ?
7      1     0  34.522824  81.457317 -54.900995  ...    ?    ?    ?    ?    ?
8      1     0  61.621550  10.968187 -69.134037  ...    ?    ?    ?    ?    ?
9      1     0  61.401356  11.014961 -69.379418  ...    ?    ?    ?    ?    ?

[10 rows x 38 columns]

In [ ]:
import numpy as np
data = data.drop(data.index[0])

#Since missing values are represented by '?', in order to do pre-processing, 
#first I am converting all '?' to Nan that is numeric type

data['X0'] = pd.to_numeric(data['X0'], errors='coerce')
data['Y0'] = pd.to_numeric(data['Y0'], errors='coerce')
data['Z0'] = pd.to_numeric(data['Z0'], errors='coerce')
data['X1'] = pd.to_numeric(data['X1'], errors='coerce')
data['Y1'] = pd.to_numeric(data['Y1'], errors='coerce')
data['Z1'] = pd.to_numeric(data['Z1'], errors='coerce')
data['X2'] = pd.to_numeric(data['X2'], errors='coerce')
data['Y2'] = pd.to_numeric(data['Y2'], errors='coerce')
data['Z2'] = pd.to_numeric(data['Z2'], errors='coerce')
data['X3'] = pd.to_numeric(data['X3'], errors='coerce')
data['Y3'] = pd.to_numeric(data['Y3'], errors='coerce')
data['Z3'] = pd.to_numeric(data['Z3'], errors='coerce')
data['X4'] = pd.to_numeric(data['X4'], errors='coerce')
data['Y4'] = pd.to_numeric(data['Y4'], errors='coerce')
data['Z4'] = pd.to_numeric(data['Z4'], errors='coerce')
data['X5'] = pd.to_numeric(data['X5'], errors='coerce')
data['Y5'] = pd.to_numeric(data['Y5'], errors='coerce')
data['Z5'] = pd.to_numeric(data['Z5'], errors='coerce')
data['X6'] = pd.to_numeric(data['X6'], errors='coerce')
data['Y6'] = pd.to_numeric(data['Y6'], errors='coerce')
data['Z6'] = pd.to_numeric(data['Z6'], errors='coerce')
data['X7'] = pd.to_numeric(data['X7'], errors='coerce')
data['Y7'] = pd.to_numeric(data['Y7'], errors='coerce')
data['Z7'] = pd.to_numeric(data['Z7'], errors='coerce')
data['X8'] = pd.to_numeric(data['X8'], errors='coerce')
data['Y8'] = pd.to_numeric(data['Y8'], errors='coerce')
data['Z8'] = pd.to_numeric(data['Z8'], errors='coerce')
data['X9'] = pd.to_numeric(data['X9'], errors='coerce')
data['Y9'] = pd.to_numeric(data['Y9'], errors='coerce')
data['Z9'] = pd.to_numeric(data['Z9'], errors='coerce')
data['X10'] = pd.to_numeric(data['X10'], errors='coerce')
data['Y10'] = pd.to_numeric(data['Y10'], errors='coerce')
data['Z10'] = pd.to_numeric(data['Z10'], errors='coerce')
data['X11'] = pd.to_numeric(data['X11'], errors='coerce')
data['Y11'] = pd.to_numeric(data['Y11'], errors='coerce')
data['Z11'] = pd.to_numeric(data['Z11'], errors='coerce')
#data.head(10)

In [ ]:
data.head(5)

   Class  User         X0         Y0         Z0  ...  Y10  Z10  X11  Y11  Z11
1      1     0  54.263880  71.466776 -64.807709  ...  NaN  NaN  NaN  NaN  NaN
2      1     0  56.527558  72.266609 -61.935252  ...  NaN  NaN  NaN  NaN  NaN
3      1     0  55.849928  72.469064 -62.562788  ...  NaN  NaN  NaN  NaN  NaN
4      1     0  55.329647  71.707275 -63.688956  ...  NaN  NaN  NaN  NaN  NaN
5      1     0  55.142401  71.435607 -64.177303  ...  NaN  NaN  NaN  NaN  NaN

[5 rows x 38 columns]

In [ ]:
#Now I am replacing all Nan values with mean of corresponding columns
new_data = data.apply(lambda x: x.fillna(x.mean()),axis=0)
new_data

       Class  User         X0  ...        X11        Y11       Z11
1          1     0  54.263880  ... -29.697613  25.963332  1.697312
2          1     0  56.527558  ... -29.697613  25.963332  1.697312
3          1     0  55.849928  ... -29.697613  25.963332  1.697312
4          1     0  55.329647  ... -29.697613  25.963332  1.697312
5          1     0  55.142401  ... -29.697613  25.963332  1.697312
...      ...   ...        ...  ...        ...        ...       ...
78091      5    14  54.251127  ... -29.697613  25.963332  1.697312
78092      5    14  54.334883  ... -29.697613  25.963332  1.697312
78093      5    14  54.151540  ... -29.697613  25.963332  1.697312
78094      5    14  27.915311  ... -29.697613  25.963332  1.697312
78095      5    14  27.898705  ... -29.697613  25.963332  1.697312

[78095 rows x 38 columns]

In [ ]:
#Since the data set was sorted in ascending order, I have used sample function to shuffle rows in dataset,
# So that while splitting dataset into train and test data, it will have values for each posture class
new_data = new_data.sample(frac=1)
new_data.head(5)

       Class  User         X0  ...        X11        Y11       Z11
71218      1    14  -4.878539  ... -29.697613  25.963332  1.697312
49459      1    11  72.596696  ... -29.697613  25.963332  1.697312
68511      4    13  55.331602  ... -29.697613  25.963332  1.697312
43503      3    10  86.008801  ... -29.697613  25.963332  1.697312
3189       2     0  62.977991  ... -29.697613  25.963332  1.697312

[5 rows x 38 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

#Here I have separated feature column and label column. 
#Since 'User' column was not giving any information, I have dropped that column 

X = new_data.drop(columns = ['Class','User'])
Y = new_data[['Class']]
print(X)

              X0          Y0         Z0  ...        X11        Y11       Z11
71218  -4.878539   77.131003 -55.049482  ... -29.697613  25.963332  1.697312
49459  72.596696   80.100018 -59.482525  ... -29.697613  25.963332  1.697312
68511  55.331602   96.183845  -3.123888  ... -29.697613  25.963332  1.697312
43503  86.008801  129.180626 -25.309659  ... -29.697613  25.963332  1.697312
3189   62.977991   14.772174 -74.003961  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
77068  57.745476  141.276733 -25.948947  ... -29.697613  25.963332  1.697312
13374  44.820239  101.330956  -4.472184  ... -29.697613  25.963332  1.697312
3023   25.114527   94.998515  17.664296  ... -29.697613  25.963332  1.697312
26863  40.314985  153.416921  -6.195313  ... -29.697613  25.963332  1.697312
66161  38.272765  130.194657 -16.481268  ... -29.697613  25.963332  1.697312

[78095 rows x 36 columns]

In [ ]:
print(Y)

       Class
71218      1
49459      1
68511      4
43503      3
3189       2
...      ...
77068      5
13374      5
3023       2
26863      4
66161      3

[78095 rows x 1 columns]

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(X, Y, train_size=0.7, random_state=25)

In [ ]:
print(train_x.shape)
print(train_y.shape)

(54666, 36)
(54666, 1)

In [ ]:
# For trying different variants in network :
#I have used different shape for each layer, also I tried various activation functions and epoch values

import tensorflow as tf
import keras
from keras import optimizers
from keras.models import Sequential
from keras import layers

model = Sequential()
model.add(layers.Dense(45, activation=tf.nn.sigmoid, input_shape=(36, )))
model.add(layers.Dense(36, activation=tf.nn.sigmoid))
model.add(layers.Dense(10, activation=tf.nn.sigmoid))
model.add(layers.Dense(25, activation=tf.nn.sigmoid))
model.add(layers.Dense(10, activation=tf.nn.softmax))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_11 (Dense)             (None, 45)                1665
_________________________________________________________________
dense_12 (Dense)             (None, 36)                1656
_________________________________________________________________
dense_13 (Dense)             (None, 10)                370
_________________________________________________________________
dense_14 (Dense)             (None, 25)                275
_________________________________________________________________
dense_15 (Dense)             (None, 10)                260
=================================================================
Total params: 4,226
Trainable params: 4,226
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_x, train_y, epochs=5)

Epoch 1/5
54666/54666 [==============================] - 3s 63us/step - loss: 1.2003 - acc: 0.5284
Epoch 2/5
54666/54666 [==============================] - 3s 60us/step - loss: 0.7264 - acc: 0.7372
Epoch 3/5
54666/54666 [==============================] - 3s 60us/step - loss: 0.5494 - acc: 0.8082
Epoch 4/5
54666/54666 [==============================] - 3s 59us/step - loss: 0.4732 - acc: 0.8346
Epoch 5/5
54666/54666 [==============================] - 3s 59us/step - loss: 0.4172 - acc: 0.8576

In [ ]:
#Here I have changed the layer shape and activation functions

model1 = Sequential()
model1.add(layers.Dense(120, activation=tf.nn.relu, input_shape=(36, )))
model1.add(layers.Dense(45, activation=tf.nn.relu))
model1.add(layers.Dense(32, activation=tf.nn.relu))
model1.add(layers.Dense(60, activation=tf.nn.softmax))

model1.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_21 (Dense)             (None, 120)               4440
_________________________________________________________________
dense_22 (Dense)             (None, 45)                5445
_________________________________________________________________
dense_23 (Dense)             (None, 32)                1472
_________________________________________________________________
dense_24 (Dense)             (None, 60)                1980
=================================================================
Total params: 13,337
Trainable params: 13,337
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model1.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model1.fit(train_x, train_y, epochs=15)

Epoch 1/15
54666/54666 [==============================] - 4s 71us/step - loss: 2.5175 - acc: 0.7229
Epoch 2/15
54666/54666 [==============================] - 4s 65us/step - loss: 0.2845 - acc: 0.9071
Epoch 3/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.2076 - acc: 0.9349
Epoch 4/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.1752 - acc: 0.9456
Epoch 5/15
54666/54666 [==============================] - 3s 64us/step - loss: 0.1506 - acc: 0.9545
Epoch 6/15
54666/54666 [==============================] - 4s 65us/step - loss: 0.1321 - acc: 0.9602
Epoch 7/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.1153 - acc: 0.9658
Epoch 8/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.1040 - acc: 0.9695
Epoch 9/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.0961 - acc: 0.9722
Epoch 10/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.0908 - acc: 0.9729
Epoch 11/15
54666/54666 [==============================] - 4s 64us/step - loss: 0.0817 - acc: 0.9760
Epoch 12/15
54666/54666 [==============================] - 4s 65us/step - loss: 0.0796 - acc: 0.9767
Epoch 13/15
54666/54666 [==============================] - 4s 64us/step - loss: 0.0768 - acc: 0.9775
Epoch 14/15
54666/54666 [==============================] - 4s 64us/step - loss: 0.0703 - acc: 0.9793
Epoch 15/15
54666/54666 [==============================] - 3s 63us/step - loss: 0.0686 - acc: 0.9794

In [ ]:
#Since with above actiavtion function and layers, I got expected accuracy, 
#here I have changed only epoch, keeping rest everying same

model1.fit(train_x, train_y, epochs=25)

Epoch 1/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0664 - acc: 0.9816
Epoch 2/25
54666/54666 [==============================] - 3s 64us/step - loss: 0.0641 - acc: 0.9819
Epoch 3/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0606 - acc: 0.9835
Epoch 4/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0585 - acc: 0.9836
Epoch 5/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0569 - acc: 0.9840
Epoch 6/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0531 - acc: 0.9841
Epoch 7/25
54666/54666 [==============================] - 3s 62us/step - loss: 0.0505 - acc: 0.9851
Epoch 8/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0429 - acc: 0.9877
Epoch 9/25
54666/54666 [==============================] - 4s 64us/step - loss: 0.0474 - acc: 0.9857
Epoch 10/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0474 - acc: 0.9862
Epoch 11/25
54666/54666 [==============================] - 4s 65us/step - loss: 0.0430 - acc: 0.9869
Epoch 12/25
54666/54666 [==============================] - 3s 64us/step - loss: 0.0420 - acc: 0.9877
Epoch 13/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0464 - acc: 0.9867
Epoch 14/25
54666/54666 [==============================] - 4s 65us/step - loss: 0.0400 - acc: 0.9876
Epoch 15/25
54666/54666 [==============================] - 3s 64us/step - loss: 0.0401 - acc: 0.9877
Epoch 16/25
54666/54666 [==============================] - 4s 65us/step - loss: 0.0370 - acc: 0.9890
Epoch 17/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0370 - acc: 0.9890
Epoch 18/25
54666/54666 [==============================] - 3s 64us/step - loss: 0.0380 - acc: 0.9884
Epoch 19/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0382 - acc: 0.9891
Epoch 20/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0372 - acc: 0.9891
Epoch 21/25
54666/54666 [==============================] - 4s 65us/step - loss: 0.0341 - acc: 0.9901
Epoch 22/25
54666/54666 [==============================] - 3s 64us/step - loss: 0.0368 - acc: 0.9888
Epoch 23/25
54666/54666 [==============================] - 3s 63us/step - loss: 0.0340 - acc: 0.9898
Epoch 24/25
54666/54666 [==============================] - 4s 64us/step - loss: 0.0353 - acc: 0.9901
Epoch 25/25
54666/54666 [==============================] - 4s 64us/step - loss: 0.0321 - acc: 0.9908

In [ ]:
from keras.utils import to_categorical

model1.evaluate(test_x, test_y)

23429/23429 [==============================] - 1s 25us/step

[0.08646194604345306, 0.9818174057817066]

In [ ]:
predictions = model1.predict(test_x[:310])
print(np.argmax(predictions, axis=1))

[4 3 2 2 1 5 2 4 4 2 4 1 3 5 5 5 2 4 1 4 5 4 1 2 2 4 2 1 5 2 4 4 1 4 2 2 3
 5 1 3 4 5 1 2 3 2 2 2 2 2 1 3 2 1 3 5 5 5 1 3 3 5 3 1 4 5 4 5 3 4 1 1 2 2
 4 5 1 4 4 5 5 1 5 1 1 5 5 1 5 5 4 5 1 3 2 3 2 3 1 5 1 4 1 2 1 4 5 3 5 2 3
 1 1 5 1 4 2 3 3 2 1 2 3 4 3 1 5 4 5 2 4 4 3 2 5 1 1 5 4 2 4 5 1 2 3 2 2 5
 2 3 1 1 5 5 5 2 3 5 1 5 3 1 1 3 2 3 5 5 2 4 3 5 3 2 2 1 2 5 4 5 1 2 5 5 1
 2 1 5 1 5 4 3 2 1 4 1 1 5 4 1 2 5 2 5 4 1 5 5 1 5 4 2 4 3 5 4 2 3 1 4 1 5
 4 2 3 3 3 5 1 1 3 2 5 1 1 3 4 1 1 4 3 5 5 2 2 4 2 4 1 3 2 3 1 4 2 4 1 1 5
 3 1 3 3 2 3 5 2 4 3 1 4 2 1 3 1 3 3 1 1 3 4 4 5 5 3 5 2 2 1 5 5 4 4 5 3 1
 1 4 4 5 4 3 1 1 1 4 2 2 3 2]

In [ ]:
# As per the values displayed, it seems that model is performing good enough in predicting the posture class based on co-ordinate values
print(test_y[:310])

       Class
47114      4
37234      3
64529      2
51576      2
14080      1
...      ...
55145      4
51258      2
19752      2
75425      3
73908      2

[310 rows x 1 columns]

In [ ]:
############################# Generator Code #################################

In [ ]:
# Here I've created a loop that breaks a dataset and put yeild inside loop to make it as a generator
def chunks_X(X):
  for g, df in X.groupby(np.arange(len(X)) // 350):
    yield df
chunk_X = chunks_X(X)

# Printing all chunks with next() function
for j in chunk_X:
    batch_x = next(chunk_X)
    print(batch_x)

              X0          Y0         Z0  ...        X11        Y11       Z11
56109  31.567127  150.892831 -15.861656  ... -29.697613  25.963332  1.697312
61116  16.402004   88.009819  23.742513  ... -29.697613  25.963332  1.697312
16368  71.368202  128.389509 -40.860105  ... -29.697613  25.963332  1.697312
68705  56.232207  137.010944 -11.716995  ... -29.697613  25.963332  1.697312
17045  66.664387   81.860900 -31.245964  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
60806  62.531701   82.341579 -17.523084  ... -29.697613  25.963332  1.697312
47851  29.020599  102.195436 -72.044843  ... -29.697613  25.963332  1.697312
36976  49.495867  144.288392 -20.896728  ... -29.697613  25.963332  1.697312
9363  -10.614350   77.872184 -37.474500  ... -29.697613  25.963332  1.697312
26568   4.761272   89.998376 -39.711644  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
8213    54.922570   63.017813 -87.715176  ... -29.697613  25.963332  1.697312
57106   33.517554   82.015285 -53.388466  ... -29.697613  25.963332  1.697312
40791   67.056154   61.175837 -83.536840  ... -29.697613  25.963332  1.697312
46833   60.091142   88.250765 -32.155039  ... -29.697613  25.963332  1.697312
42590   58.261144  139.445847  41.169002  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
64930   13.094656   88.785087   7.370236  ... -29.697613  25.963332  1.697312
30483   10.930637   93.695960  10.704994  ... -29.697613  25.963332  1.697312
29081   58.390373    1.612832 -84.187991  ... -29.697613  25.963332  1.697312
21442  -15.199135  100.722806   6.556924  ... -29.697613  25.963332  1.697312
12981  125.747034   27.255733 -15.780141  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
74433   18.532328  113.546065 -12.019540  ... -29.697613  25.963332  1.697312
13772   40.749873   75.170459 -53.690850  ... -29.697613  25.963332  1.697312
28857   60.883445    0.358915 -81.982460  ... -29.697613  25.963332  1.697312
38649  109.477481   63.453265 -49.754515  ... -29.697613  25.963332  1.697312
22      77.783316   42.846996 -71.753913  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
56868   91.946849   41.402239 -49.914616  ... -29.697613  25.963332  1.697312
4520    90.023404   41.076383 -92.628705  ... -29.697613  25.963332  1.697312
53256   10.399110   86.105406 -31.235334  ... -29.697613  25.963332  1.697312
20644   34.658504  145.792600  20.789213  ... -29.697613  25.963332  1.697312
53785   92.461334   28.966228 -60.388297  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
27414  52.520372   95.456358   0.000622  ... -29.697613  25.963332  1.697312
67609  60.357313  135.471182   3.189570  ... -29.697613  25.963332  1.697312
13739  66.654016   95.626457 -22.012391  ... -29.697613  25.963332  1.697312
793    73.379657   52.141426 -68.431132  ... -29.697613  25.963332  1.697312
13921  35.359196   72.048447 -61.013763  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
4420   58.773491   89.668699 -38.851220  ... -29.697613  25.963332  1.697312
24655  58.622776   91.530437  -0.012851  ... -29.697613  25.963332  1.697312
39383  33.372636   75.595241 -59.820328  ... -29.697613  25.963332  1.697312
48697  36.114590  107.622542 -59.763695  ... -29.697613  25.963332  1.697312
33165  50.285096  154.690854 -18.443846  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
67392  57.995724   94.804050  -1.146148  ... -29.697613  25.963332  1.697312
43980  86.487251  129.271242 -24.614003  ... -29.697613  25.963332  1.697312
11730  78.153537   40.909381 -51.125574  ... -29.697613  25.963332  1.697312
47297  29.437464    7.312640   9.169847  ... -29.697613  25.963332  1.697312
53728  54.087208   92.715424   4.971765  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
45956  84.204922    3.839781 -88.305571  ... -29.697613  25.963332  1.697312
72495  52.887822  150.244280  19.938250  ... -29.697613  25.963332  1.697312
76700  68.333449  132.269883  30.877877  ... -29.697613  25.963332  1.697312
73205  67.308691  139.204812  10.470786  ... -29.697613  25.963332  1.697312
13524  48.278144  100.177824  -1.080697  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
62760  54.085348   76.767435 -72.814848  ... -29.697613  25.963332  1.697312
3181   99.180144   36.308315 -87.682055  ... -29.697613  25.963332  1.697312
40184  -7.284386   72.897859 -36.872006  ... -29.697613  25.963332  1.697312
71514   9.392841   77.772874 -55.904774  ... -29.697613  25.963332  1.697312
12154  36.342393  164.279546 -30.278376  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
14412  43.568579   74.593366 -53.144961  ... -29.697613  25.963332  1.697312
25128  57.977071   91.627195   0.759017  ... -29.697613  25.963332  1.697312
21626  15.158405  158.317590  13.597926  ... -29.697613  25.963332  1.697312
20108  40.434675  139.961236  17.875452  ... -29.697613  25.963332  1.697312
41551  73.871980   35.078439 -84.840969  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
32028  71.065204  132.149120 -19.327180  ... -29.697613  25.963332  1.697312
65444   2.348323   76.204088  40.584584  ... -29.697613  25.963332  1.697312
7631   50.504324   32.044136 -71.427008  ... -29.697613  25.963332  1.697312
39488  31.606780   76.192470 -60.117041  ... -29.697613  25.963332  1.697312
29267  34.400167   73.737384 -57.387808  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
22250  33.996143   97.385227  -4.554059  ... -29.697613  25.963332  1.697312
5800   52.033096   94.548524 -45.474321  ... -29.697613  25.963332  1.697312
25369  88.211232   43.741001 -72.552879  ... -29.697613  25.963332  1.697312
37732  47.034370   98.418245 -11.280090  ... -29.697613  25.963332  1.697312
67425  60.867287   94.136155   0.338156  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
33343  42.301378  154.691091 -33.170873  ... -29.697613  25.963332  1.697312
2627  -10.102989   94.452998   8.141550  ... -29.697613  25.963332  1.697312
47215  58.209409   87.562101 -35.934952  ... -29.697613  25.963332  1.697312
34525  65.423325   81.362107 -77.751900  ... -29.697613  25.963332  1.697312
48400  29.709606    1.892085   2.492862  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
66153  45.392061   91.915102 -14.999158  ... -29.697613  25.963332  1.697312
40646  68.651499   59.049046 -86.064386  ... -29.697613  25.963332  1.697312
37226  75.316168   85.995019 -16.299118  ... -29.697613  25.963332  1.697312
6227  -14.351131   53.519948 -61.877555  ... -29.697613  25.963332  1.697312
31235  66.917602  134.697967 -25.601818  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
6311     1.021156   38.734657 -97.249888  ... -29.697613  25.963332  1.697312
64531    2.670739  114.823876  19.827101  ... -29.697613  25.963332  1.697312
76228   73.959976   32.048246 -47.030482  ... -29.697613  25.963332  1.697312
58310  -73.144285  -33.852907 -43.071162  ... -29.697613  25.963332  1.697312
25809  108.830565   44.140335 -60.943803  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
37990   78.267228   85.428517 -24.553872  ... -29.697613  25.963332  1.697312
66712   48.563782   94.354771 -16.114498  ... -29.697613  25.963332  1.697312
54965   26.323110   94.007975 -37.459557  ... -29.697613  25.963332  1.697312
7622    58.306323   62.176016 -83.738972  ... -29.697613  25.963332  1.697312
6725    -5.573679   61.532699 -55.835032  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
45460   69.056391  134.735248 -43.953222  ... -29.697613  25.963332  1.697312
27168   79.617811   86.104477 -20.343378  ... -29.697613  25.963332  1.697312
68637   53.601219   97.271019 -13.313729  ... -29.697613  25.963332  1.697312
4184    60.351172   89.660738 -37.648591  ... -29.697613  25.963332  1.697312
12739   41.316707  102.464517  -5.642360  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
3281    -3.213331  118.890447  43.453935  ... -29.697613  25.963332  1.697312
29839    6.842924   91.355905  15.647505  ... -29.697613  25.963332  1.697312
40356   11.198399   73.867554 -52.097715  ... -29.697613  25.963332  1.697312
16104  109.036279   46.782845 -67.338943  ... -29.697613  25.963332  1.697312
55664   95.115877   37.999245 -55.559467  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
45511   79.761835    9.287614 -92.954056  ... -29.697613  25.963332  1.697312
74020   43.634634  101.651887  13.705504  ... -29.697613  25.963332  1.697312
14427   38.091005   74.248473 -58.249812  ... -29.697613  25.963332  1.697312
46119  106.164301   14.485717 -89.367500  ... -29.697613  25.963332  1.697312
22382   35.692009   96.680243  -3.220967  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
6138     3.970613   65.986778 -62.425680  ... -29.697613  25.963332  1.697312
16583  108.612373   45.670452 -67.808071  ... -29.697613  25.963332  1.697312
15341   70.691114   86.842225  -9.578249  ... -29.697613  25.963332  1.697312
8995    48.718482   20.496449 -76.812246  ... -29.697613  25.963332  1.697312
57803   31.375096   85.204513  13.871125  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
42230   89.832857   77.988416 -24.717170  ... -29.697613  25.963332  1.697312
33228   48.070181  153.213464 -27.244531  ... -29.697613  25.963332  1.697312
38579    9.758452  103.611141   5.173896  ... -29.697613  25.963332  1.697312
74751   81.183128   45.427690 -43.050576  ... -29.697613  25.963332  1.697312
67330   60.912404   93.935020   4.598717  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
2469    36.165436  108.230811  -9.405772  ... -29.697613  25.963332  1.697312
9109    30.004809   86.685970 -49.828085  ... -29.697613  25.963332  1.697312
20427   44.244947  138.089102  20.607835  ... -29.697613  25.963332  1.697312
16357  107.243843   44.995550 -69.763493  ... -29.697613  25.963332  1.697312
68550   55.073156   96.807375 -11.737031  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
48503  14.379968   92.052812 -77.508155  ... -29.697613  25.963332  1.697312
58164  55.069261   80.010362  13.069176  ... -29.697613  25.963332  1.697312
6489   -2.541876   37.724252 -95.730847  ... -29.697613  25.963332  1.697312
14847  35.775812   77.012557 -55.938748  ... -29.697613  25.963332  1.697312
407    59.164627   10.809834 -71.082274  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
52165  47.491359   96.288295 -13.161050  ... -29.697613  25.963332  1.697312
6540   10.106097   71.047479 -58.002736  ... -29.697613  25.963332  1.697312
3293   74.450089   92.038056  -7.548923  ... -29.697613  25.963332  1.697312
62594  31.434850   79.892613 -44.673286  ... -29.697613  25.963332  1.697312
60298  46.417756  151.592929 -18.919466  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0          Z0  ...        X11        Y11       Z11
45835   69.089290  145.787557  -21.833765  ... -29.697613  25.963332  1.697312
46048  105.074676   10.647336  -90.695844  ... -29.697613  25.963332  1.697312
46815   61.245281   88.072117  -30.954931  ... -29.697613  25.963332  1.697312
66564   41.242385  133.007524  -16.131249  ... -29.697613  25.963332  1.697312
31083   81.536545   56.646838  -76.066432  ... -29.697613  25.963332  1.697312
...           ...         ...         ...  ...        ...        ...       ...
11806   48.980567  143.866150  -16.916309  ... -29.697613  25.963332  1.697312
41739   72.498636   33.853418  -85.793805  ... -29.697613  25.963332  1.697312
56403  -28.277321  106.614751  -66.654927  ... -29.697613  25.963332  1.697312
74368   22.628223  112.516697  -12.925524  ... -29.697613  25.963332  1.697312
8278    52.502400   82.996813 -100.455630  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
19659  38.868073   92.965476   0.158490  ... -29.697613  25.963332  1.697312
4893   80.333899   82.921609 -63.667395  ... -29.697613  25.963332  1.697312
50020  68.888990   19.984269 -55.839269  ... -29.697613  25.963332  1.697312
61398 -14.655048   88.436051   8.407865  ... -29.697613  25.963332  1.697312
66705  43.353924  130.171052 -24.107536  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
7071   58.089461   53.696472 -91.618594  ... -29.697613  25.963332  1.697312
12110 -11.387694   84.862883 -29.555001  ... -29.697613  25.963332  1.697312
38066  77.364974   84.997056 -26.078084  ... -29.697613  25.963332  1.697312
50700  16.890046   99.523060 -30.334196  ... -29.697613  25.963332  1.697312
8651   57.949714   69.940372 -78.767058  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
37902  78.389408    5.989783 -61.158880  ... -29.697613  25.963332  1.697312
10306   8.225579   81.394482 -44.942874  ... -29.697613  25.963332  1.697312
68050  58.225914   95.202093  -1.633588  ... -29.697613  25.963332  1.697312
2309   99.225332   73.540088 -69.117195  ... -29.697613  25.963332  1.697312
51001  83.586741  132.110076  -6.757545  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
71676 -16.264811   81.064570 -11.045558  ... -29.697613  25.963332  1.697312
18508  60.216209   77.650656 -37.373806  ... -29.697613  25.963332  1.697312
18174  83.056058   20.365203 -66.595050  ... -29.697613  25.963332  1.697312
16709  66.298052   81.968204 -31.897743  ... -29.697613  25.963332  1.697312
16140  19.638567   78.734841 -49.176960  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
73239  21.838175  140.719293  40.177926  ... -29.697613  25.963332  1.697312
21611  15.962878  100.991424   4.205840  ... -29.697613  25.963332  1.697312
21363  33.762954  147.186022  17.542328  ... -29.697613  25.963332  1.697312
41806  68.564552  137.798238  33.182891  ... -29.697613  25.963332  1.697312
38109  87.242895  127.557434 -22.755847  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
77726  79.799079   31.116033 -47.831167  ... -29.697613  25.963332  1.697312
71752  51.826706   79.569099  58.956397  ... -29.697613  25.963332  1.697312
71573  13.138450   78.751699 -54.374195  ... -29.697613  25.963332  1.697312
54010  53.643963   92.898099   1.455925  ... -29.697613  25.963332  1.697312
28526  88.681536  -24.333189 -46.439263  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
51391  104.018709   50.292120 -44.111108  ... -29.697613  25.963332  1.697312
37457   76.719524  129.438791 -14.539316  ... -29.697613  25.963332  1.697312
18449   60.255495   66.425395 -51.553915  ... -29.697613  25.963332  1.697312
73830   55.183197  147.078272  26.598363  ... -29.697613  25.963332  1.697312
73126   55.704862  146.375298  27.528744  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
1463    11.585265   92.113413 -31.555631  ... -29.697613  25.963332  1.697312
56638   67.318135  135.145843 -23.924883  ... -29.697613  25.963332  1.697312
57633   12.313413   83.130290 -40.029961  ... -29.697613  25.963332  1.697312
62661   55.115876   79.823260 -69.589153  ... -29.697613  25.963332  1.697312
68676   74.570367   48.119939 -57.792724  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
               X0          Y0         Z0  ...        X11        Y11       Z11
7899    52.877194   19.249370 -76.026938  ... -29.697613  25.963332  1.697312
74197   53.259663  139.356157  26.159445  ... -29.697613  25.963332  1.697312
18733   36.110097  100.658451   8.137977  ... -29.697613  25.963332  1.697312
16568  108.238001   45.667403 -67.879065  ... -29.697613  25.963332  1.697312
21089   34.694654  146.954120  16.942443  ... -29.697613  25.963332  1.697312
...           ...         ...        ...  ...        ...        ...       ...
8436    68.408426  126.444099 -67.060817  ... -29.697613  25.963332  1.697312
64138   19.976843  137.734375  16.907663  ... -29.697613  25.963332  1.697312
10828   99.077421   56.596045 -66.532697  ... -29.697613  25.963332  1.697312
60520   62.837421   81.783925 -15.575044  ... -29.697613  25.963332  1.697312
60210   65.824426  133.797972 -13.263741  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
12638  92.179110  137.561075  16.738577  ... -29.697613  25.963332  1.697312
24341  55.986582   81.351246 -37.832395  ... -29.697613  25.963332  1.697312
19831  48.272265  134.833555  23.922711  ... -29.697613  25.963332  1.697312
64315  55.615042   88.405733   8.342877  ... -29.697613  25.963332  1.697312
4400   50.876327  133.425635 -49.720292  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
66011  50.833025  131.605085 -22.285107  ... -29.697613  25.963332  1.697312
29639  58.027929   70.510573 -63.942002  ... -29.697613  25.963332  1.697312
44240  59.956633   -4.573537 -79.935641  ... -29.697613  25.963332  1.697312
6503    9.730491   71.763453 -57.671867  ... -29.697613  25.963332  1.697312
2623  -10.987611   94.914509   7.952797  ... -29.697613  25.963332  1.697312

[350 rows x 36 columns]
              X0          Y0         Z0  ...        X11        Y11       Z11
14239  17.044910   77.291213 -50.045954  ... -29.697613  25.963332  1.697312
67555  61.456082  135.054457   6.119859  ... -29.697613  25.963332  1.697312
67797  60.927284  135.100796   1.586127  ... -29.697613  25.963332  1.697312
22446  31.437864  145.247465   6.366672  ... -29.697613  25.963332  1.697312
63712  64.501885   52.789195 -62.667006  ... -29.697613  25.963332  1.697312
...          ...         ...        ...  ...        ...        ...       ...
59934  40.469994   88.103604  -4.623502  ... -29.697613  25.963332  1.697312
57443  33.041918   81.787839 -54.233217  ... -29.697613  25.963332  1.697312
9758    9.748177   84.123616 -46.905304  ... -29.697613  25.963332  1.697312
73917  54.785195  147.369415  25.563323  ... -29.697613  25.963332  1.697312

In [ ]:
# Repeating same steps of generator for labels

def chunks_Y(Y):
  for g, df in Y.groupby(np.arange(len(Y)) // 350):
    yield df
chunk_Y = chunks_Y(Y)

for j in chunk_Y:
    batch_y = next(chunk_Y)
    print(batch_y)

       Class
56109      5
61116      5
16368      3
68705      4
17045      4
...      ...
60806      4
47851      5
36976      2
9363       1
26568      4

[350 rows x 1 columns]
       Class
8213       5
57106      1
40791      1
46833      4
42590      2
...      ...
64930      2
30483      2
29081      1
21442      3
12981      5

[350 rows x 1 columns]
       Class
74433      3
13772      1
28857      1
38649      5
22         1
...      ...
56868      5
4520       3
53256      3
20644      3
53785      4

[350 rows x 1 columns]
       Class
27414      5
67609      4
13739      5
793        1
13921      1
...      ...
4420       3
24655      2
39383      1
48697      5
33165      4

[350 rows x 1 columns]
       Class
67392      4
43980      3
11730      3
47297      5
53728      4
...      ...
45956      4
72495      2
76700      4
73205      2
13524      5

[350 rows x 1 columns]
       Class
62760      1
3181       2
40184      1
71514      1
12154      4
...      ...
14412      1
25128      2
21626      4
20108      2
41551      1

[350 rows x 1 columns]
       Class
32028      3
65444      2
7631       5
39488      1
29267      1
...      ...
22250      4
5800       4
25369      2
37732      4
67425      4

[350 rows x 1 columns]
       Class
33343      4
2627       2
47215      4
34525      5
48400      5
...      ...
66153      3
40646      1
37226      3
6227       4
31235      3

[350 rows x 1 columns]
       Class
6311       4
64531      2
76228      4
58310      2
25809      3
...      ...
37990      4
66712      3
54965      4
7622       5
6725       4

[350 rows x 1 columns]
       Class
45460      4
27168      5
68637      4
4184       3
12739      5
...      ...
3281       2
29839      2
40356      1
16104      3
55664      5

[350 rows x 1 columns]
       Class
45511      4
74020      2
14427      1
46119      4
22382      4
...      ...
6138       4
16583      4
15341      2
8995       5
57803      2

[350 rows x 1 columns]
       Class
42230      2
33228      4
38579      5
74751      3
67330      4
...      ...
2469       2
9109       1
20427      2
16357      3
68550      4

[350 rows x 1 columns]
       Class
48503      5
58164      2
6489       4
14847      1
407        1
...      ...
52165      3
6540       4
3293       2
62594      1
60298      4

[350 rows x 1 columns]
       Class
45835      4
46048      4
46815      4
66564      3
31083      2
...      ...
11806      3
41739      1
56403      5
74368      3
8278       5

[350 rows x 1 columns]
       Class
19659      2
4893       3
50020      1
61398      5
66705      3
...      ...
7071       5
12110      3
38066      4
50700      2
8651       5

[350 rows x 1 columns]
       Class
37902      4
10306      1
68050      4
2309       2
51001      2
...      ...
71676      1
18508      3
18174      5
16709      4
16140      3

[350 rows x 1 columns]
       Class
73239      2
21611      4
21363      3
41806      2
38109      4
...      ...
77726      5
71752      1
71573      1
54010      4
28526      4

[350 rows x 1 columns]
       Class
51391      2
37457      3
18449      3
73830      2
73126      2
...      ...
1463       1
56638      5
57633      1
62661      1
68676      4

[350 rows x 1 columns]
       Class
7899       5
74197      3
18733      1
16568      4
21089      3
...      ...
8436       5
64138      2
10828      2
60520      4
60210      4

[350 rows x 1 columns]
       Class
12638      4
24341      1
19831      2
64315      2
4400       3
...      ...
66011      3
29639      1
44240      3
6503       4
2623       2

[350 rows x 1 columns]
       Class
14239      1
67555      4
67797      4
22446      4
63712      1
...      ...
59934      4
57443      1
9758       1
73917      2
6824       4

[350 rows x 1 columns]
       Class
51478      2
53875      4
34353      5
68263      4
26452      4
...      ...
35821      1
69996      5
64302      2
15980      3
55802      5

[350 rows x 1 columns]
       Class
37121      3
1917       2
23773      1
17181      5
20840      3
...      ...
69620      5
55349      4
71905      1
23800      1
33892      4

[350 rows x 1 columns]
       Class
62171      1
23948      1
61361      5
21796      4
57988      2
...      ...
11082      2
32649      3
61318      5
71193      1
40358      1

[350 rows x 1 columns]
       Class
50134      1
58663      3
23075      5
22859      5
33737      4
...      ...
16891      4
21770      4
1271       1
21498      3
43667      3

[350 rows x 1 columns]
       Class
49249      1
28284      2
17479      5
70896      1
15661      2
...      ...
23403      5
31729      3
2219       2
66074      3
58504      2

[350 rows x 1 columns]
       Class
42461      2
33760      4
63391      1
36797      2
56876      5
...      ...
76872      4
39041      5
8475       5
12835      5
26252      4

[350 rows x 1 columns]
       Class
27231      5
23683      5
9393       1
53221      3
67963      4
...      ...
57936      2
28455      3
67498      4
6182       4
48333      5

[350 rows x 1 columns]
       Class
35707      1
30857      2
5379       4
34364      5
20317      2
...      ...
72328      2
71385      1
28454      3
32775      3
72155      1

[350 rows x 1 columns]
       Class
10298      1
54961      4
56123      5
14193      1
39319      5
...      ...
38440      4
14957      1
39684      1
27813      5
59366      3

[350 rows x 1 columns]
       Class
25457      2
67991      4
45206      3
893        1
17593      5
...      ...
1248       1
54828      4
10071      1
16691      4
30621      2

[350 rows x 1 columns]
       Class
47256      5
9522       1
13059      5
44462      3
62046      1
...      ...
68180      4
8251       5
25664      3
1311       1
15554      2

[350 rows x 1 columns]
       Class
45082      3
37059      3
60466      4
60172      4
39094      5
...      ...
25458      2
39102      5
19911      2
2078       2
60580      4

[350 rows x 1 columns]
       Class
56304      5
77766      5
53331      3
76850      4
57208      1
...      ...
56195      5
27107      5
12381      4
71427      1
10695      2

[350 rows x 1 columns]
       Class
28068      5
74123      3
21473      3
6607       4
71213      1
...      ...
74129      3
28202      1
13182      5
69371      5
13579      5

[350 rows x 1 columns]
       Class
488        1
43558      3
20154      2
4387       3
40243      1
...      ...
51941      3
62423      1
24213      1
57257      1
7452       5

[350 rows x 1 columns]
       Class
42376      2
37431      3
33796      4
72881      2
25666      3
...      ...
1035       1
38241      4
20102      2
50958      2
59532      3

[350 rows x 1 columns]
       Class
63350      1
40139      1
3734       3
14269      1
28534      4
...      ...
51182      2
9399       1
9365       1
41408      1
73488      2

[350 rows x 1 columns]
       Class
9833       1
65723      3
66714      3
32151      3
9294       1
...      ...
34262      5
7117       5
29476      1
51598      2
1796       1

[350 rows x 1 columns]
       Class
2243       2
19879      2
42144      2
43193      2
16385      3
...      ...
480        1
33275      4
73175      2
17130      4
52404      3

[350 rows x 1 columns]
       Class
26857      4
35096      5
38501      4
34071      5
18721      1
...      ...
49500      1
65978      3
9616       1
56603      5
4690       3

[350 rows x 1 columns]
       Class
15462      2
38351      4
49218      1
42402      2
28035      5
...      ...
70698      1
43082      2
55355      4
31273      3
76956      4

[350 rows x 1 columns]
       Class
1309       1
66235      3
71394      1
45438      4
11985      3
...      ...
28938      1
16772      4
59674      3
17919      5
22691      5

[350 rows x 1 columns]
       Class
65838      3
38660      5
14093      1
22658      5
8583       5
...      ...
44608      3
44670      3
33742      4
45793      4
69005      4

[350 rows x 1 columns]
       Class
51306      2
5171       3
57041      1
1042       1
60560      4
...      ...
16980      4
30633      2
30269      2
35069      5
1930       2

[350 rows x 1 columns]
       Class
48835      5
22735      5
72352      2
71024      1
42297      2
...      ...
43860      3
32011      3
77111      5
12312      4
43433      3

[350 rows x 1 columns]
       Class
15623      2
40284      1
15521      2
72871      2
288        1
...      ...
66807      3
66300      3
28610      4
57422      1
64806      2

[350 rows x 1 columns]
       Class
10538      2
28030      5
19236      1
24923      2
64556      2
...      ...
44318      3
77881      5
1093       1
42148      2
6614       4

[350 rows x 1 columns]
       Class
20669      3
33062      4
26661      4
53127      3
21725      4
...      ...
20082      2
57068      1
37         1
34384      5
62194      1

[350 rows x 1 columns]
       Class
32367      3
65361      2
71113      1
54620      4
53638      4
...      ...
42711      2
68954      4
55018      4
2973       2
37219      3

[350 rows x 1 columns]
       Class
23824      1
60181      4
59656      3
8996       5
67933      4
...      ...
48484      5
8826       5
69085      5
46047      4
18204      5

[350 rows x 1 columns]
       Class
17391      5
2815       2
36344      2
31382      3
63117      1
...      ...
40910      1
69905      5
32038      3
24657      2
57343      1

[350 rows x 1 columns]
       Class
66070      3
73659      2
62371      1
23474      5
73974      2
...      ...
35302      5
56150      5
33007      4
15398      2
11651      3

[350 rows x 1 columns]
       Class
22074      4
6265       4
7308       5
41023      1
45217      3
...      ...
13386      5
77136      5
9726       1
65403      2
8650       5

[350 rows x 1 columns]
       Class
2224       2
55475      5
69702      5
15330      2
23768      1
...      ...
73997      2
77119      5
8040       5
19087      1
25410      2

[350 rows x 1 columns]
       Class
59128      3
47332      5
4927       3
59210      3
69252      5
...      ...
43843      3
48258      5
67866      4
33997      5
33207      4

[350 rows x 1 columns]
       Class
68642      4
63950      1
6283       4
44483      3
47198      4
...      ...
38676      5
52889      3
70485      5
58253      2
12939      5

[350 rows x 1 columns]
       Class
56378      5
64935      2
40066      1
70376      5
43852      3
...      ...
61699      5
48948      1
51920      3
8762       5
57249      1

[350 rows x 1 columns]
       Class
47610      5
59154      3
54743      4
13547      5
75370      3
...      ...
6846       4
74871      3
49850      1
19436      1
58989      3

[350 rows x 1 columns]
       Class
44407      3
24770      2
52958      3
18785      1
66162      3
...      ...
33252      4
36769      2
20623      3
50979      2
70864      1

[350 rows x 1 columns]
       Class
77135      5
13881      1
51865      2
29063      1
44606      3
...      ...
56552      5
15882      3
42475      2
22071      4
25924      3

[350 rows x 1 columns]
       Class
24155      1
10897      2
38594      5
9097       1
71139      1
...      ...
54399      4
3100       2
77144      5
52457      3
28889      1

[350 rows x 1 columns]
       Class
76243      4
13051      5
22854      5
20330      2
16586      4
...      ...
25936      3
48995      1
76719      4
72446      2
34651      5

[350 rows x 1 columns]
       Class
17224      5
34385      5
32583      3
59090      3
33957      5
...      ...
14148      1
51190      2
43269      3
19901      2
53896      4

[350 rows x 1 columns]
       Class
65122      2
45253      3
60050      4
44725      3
18941      1
...      ...
37201      3
31771      3
27101      5
69804      5
65976      3

[350 rows x 1 columns]
       Class
9186       1
77707      5
62860      1
23991      1
18021      5
...      ...
61974      1
50947      2
56051      5
49285      1
11694      3

[350 rows x 1 columns]
       Class
49190      1
46845      4
74472      3
63036      1
61803      5
...      ...
41735      1
21560      4
59239      3
8795       5
60399      4

[350 rows x 1 columns]
       Class
32622      3
44353      3
11920      3
76786      4
39688      1
...      ...
20797      3
72701      2
52707      3
55969      5
6749       4

[350 rows x 1 columns]
       Class
50526      1
19470      1
9273       1
62648      1
41094      1
...      ...
66823      3
9256       1
6161       4
63226      1
69079      4

[350 rows x 1 columns]
       Class
24290      1
50987      2
42540      2
52518      3
14099      1
...      ...
34592      5
10584      2
41355      1
11442      3
71980      1

[350 rows x 1 columns]
       Class
44255      3
23852      1
46844      4
30353      2
60614      4
...      ...
29358      1
35396      5
16318      3
1262       1
26164      3

[350 rows x 1 columns]
       Class
52880      3
19989      2
66620      3
28895      1
51257      2
...      ...
54515      4
41099      1
35831      1
26348      4
37402      3

[350 rows x 1 columns]
       Class
46575      4
1508       1
33187      4
65241      2
35924      1
...      ...
8504       5
15374      2
67604      4
74987      3
2335       2

[350 rows x 1 columns]
       Class
32341      3
75994      3
27463      5
6459       4
69426      5
...      ...
25153      2
29492      1
62579      1
27774      5
16047      3

[350 rows x 1 columns]
       Class
72873      2
72958      2
44095      3
53350      3
19491      2
...      ...
60308      4
44722      3
45179      3
71984      1
55415      5

[350 rows x 1 columns]
       Class
1980       2
46332      4
76333      4
45002      3
62766      1
...      ...
60038      4
8892       5
8837       5
54493      4
22023      4

[350 rows x 1 columns]
       Class
49280      1
37944      4
22699      5
1470       1
61234      5
...      ...
45689      4
77163      5
4407       3
39618      1
19722      2

[350 rows x 1 columns]
       Class
4036       3
36765      2
40960      1
10511      2
52190      3
...      ...
76695      4
70032      5
77344      5
44706      3
26357      4

[350 rows x 1 columns]
       Class
25012      2
15391      2
8390       5
46456      4
32710      3
...      ...
70909      1
28581      4
13247      5
18926      1
43994      3

[350 rows x 1 columns]
       Class
8734       5
17962      5
69065      4
3317       2
15548      2
...      ...
74062      3
64139      2
31444      3
66654      3
47281      5

[350 rows x 1 columns]
       Class
3024       2
18420      3
34847      5
10868      2
44713      3
...      ...
43397      3
16596      4
12910      5
19240      1
19161      1

[350 rows x 1 columns]
       Class
64954      2
27202      5
50717      2
49006      1
30473      2
...      ...
76886      4
26525      4
25284      2
1390       1
17525      5

[350 rows x 1 columns]
       Class
48207      5
36186      2
19564      2
273        1
33601      4
...      ...
50819      2
38323      4
11485      3
46719      4
43331      3

[350 rows x 1 columns]
       Class
57938      2
25222      2
38819      5
71116      1
29655      1
...      ...
45611      4
33024      4
57812      2
32130      3
16474      3

[350 rows x 1 columns]
       Class
35442      5
18436      3
24964      2
39585      1
51706      2
...      ...
37972      4
43038      2
45568      4
74602      3
33898      4

[350 rows x 1 columns]
       Class
33708      4
60488      4
49770      1
25370      2
69531      5
...      ...
54001      4
54064      4
5940       4
69638      5
64870      2

[350 rows x 1 columns]
       Class
71261      1
42814      2
59116      3
17908      5
41215      1
...      ...
74186      3
60052      4
13702      5
62239      1
21452      3

[350 rows x 1 columns]
       Class
688        1
58163      2
34194      5
21417      3
8571       5
...      ...
23325      5
16012      3
41102      1
59472      3
11287      3

[350 rows x 1 columns]
       Class
46387      4
52070      3
33466      4
46694      4
71537      1
...      ...
17222      5
24968      2
69129      5
38114      4
620        1

[350 rows x 1 columns]
       Class
41452      1
56944      5
4962       3
77835      5
48717      5
...      ...
24758      2
56506      5
47037      4
59640      3
74783      3

[350 rows x 1 columns]
       Class
53923      4
50997      2
62470      1
65240      2
16640      4
...      ...
15909      3
24546      2
12012      3
25720      3
8664       5

[350 rows x 1 columns]
       Class
14084      1
17591      5
73754      2
37159      3
77566      5
...      ...
4121       3
64583      2
30332      2
37870      4
25999      3

[350 rows x 1 columns]
       Class
67033      3
20631      3
64900      2
40414      1
36943      2
...      ...
39112      5
12583      4
71079      1
16500      4
31475      3

[350 rows x 1 columns]
       Class
75358      3
76095      4
10598      2
52998      3
71384      1
...      ...
34323      5
57742      2
36227      2
18051      5
75595      3

[350 rows x 1 columns]
       Class
52387      3
34358      5
59545      3
66144      3
51653      2
...      ...
32206      3
11246      3
46764      4
61767      5
23620      5

[350 rows x 1 columns]
       Class
49081      1
51036      2
65768      3
31354      3
39216      5
...      ...
58924      3
37395      3
33376      4
40361      1
13298      5

[350 rows x 1 columns]
       Class
27829      5
41955      2
42182      2
68231      4
31385      3
...      ...
55309      4
39212      5
45238      3
56897      5
37782      4

[350 rows x 1 columns]
       Class
72900      2
30376      2
57822      2
25250      2
10680      2
...      ...
6740       4
26571      4
18127      5
23350      5
37830      4

[350 rows x 1 columns]
       Class
43941      3
31622      3
65178      2
68937      4
38842      5
...      ...
60207      4
70155      5
43047      2
11346      3
43266      3

[350 rows x 1 columns]
       Class
27969      5
4869       3
57321      1
60597      4
11210      3
...      ...
63908      1
32116      3
31839      3
1196       1
61870      1

[350 rows x 1 columns]
       Class
47015      4
75382      3
54647      4
47652      5
63336      1
...      ...
21177      3
15410      2
73545      2
60125      4
56026      5

[350 rows x 1 columns]
       Class
51457      2
21687      4
18669      1
59816      4
45366      4
...      ...
5739       4
39427      1
46245      4
1838       1
77635      5

[350 rows x 1 columns]
       Class
26376      4
22455      4
55538      5
3639       3
58728      3
...      ...
56933      5
50406      1
65022      2
52884      3
49796      1

[350 rows x 1 columns]
       Class
78080      5
73013      2
6978       4
73732      2
4819       3
...      ...
53902      4
18564      4
5504       4
9631       1
64020      2

[350 rows x 1 columns]
       Class
44220      3
51033      2
1203       1
60969      5
12379      4
...      ...
17488      5
1671       1
57664      1
26106      3
70594      5

[350 rows x 1 columns]
       Class
43477      3
11390      3
3761       3
9568       1
64425      2
...      ...
73071      2
22701      5
54714      4
33849      4
11670      3

[350 rows x 1 columns]
       Class
52504      3
68288      4
35595      1
18333      2
23721      5
...      ...
25529      3
61859      5
15886      3
16227      3
1306       1

[350 rows x 1 columns]
       Class
53377      3
61780      5
50877      2
75729      3
28511      4
...      ...
37082      3
9245       1
40059      1
29453      1
310        1

[350 rows x 1 columns]
       Class
3830       3
77069      5
54969      4
70529      5
51400      2
...      ...
76171      4
32273      3
44582      3
36253      2
72422      2

[350 rows x 1 columns]
       Class
16911      4
6159       4
10667      2
24589      2
25080      2
...      ...
40626      1
52120      3
4677       3
10931      2
15508      2

[350 rows x 1 columns]
       Class
48132      5
60332      4
64318      2
31686      3
42805      2
...      ...
18033      5
14563      1
43960      3
31852      3
41721      1

[350 rows x 1 columns]
       Class

In [ ]:
print(type(batch_x))
print(type(batch_y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
# Here I am randomly updating 10 values in each batch with 0 as an augmentation technique
#Since last batch has shape (45,36), I have used if-else to take care of batch shape
#In the end I am concatenating all batches to create new data frame which has 0 at random indices
df_n = pd.DataFrame(columns=['X0','Y0','Z0','X1','Y1','Z1','X2','Y2','Z2','X3','Y3','Z3','X4','Y4','Z4','X5','Y5','Z5',
                              'X6','Y6','Z6','X7','Y7','Z7','X8','Y8','Z8','X9','Y9','Z9','X10','Y10','Z10','X11','Y11','Z11'])
df_y = pd.DataFrame(columns=['Class'])

chunk_X = chunks_X(X)
for j in chunk_X:
  batch_x = next(chunk_X)
  for i in range(0,10):
    if(batch_x.shape == (45,36)):
      n = np.random.randint(1,45)
      m = np.random.randint(1,36)
    else:
      n = np.random.randint(1,350)
      m = np.random.randint(1,36)
  batch_x.iat[n,m] = 0
  df_interpolated = batch_x
  df_n = pd.concat([df_n,df_interpolated])


chunk_Y = chunks_Y(Y)
for i in chunk_Y:
  batch_y = next(chunk_Y)
  df_y = pd.concat([df_y,batch_y])

In [ ]:
df_n.head(10)

              X0          Y0         Z0  ...        X11        Y11       Z11
56109  31.567127  150.892831 -15.861656  ... -29.697613  25.963332  1.697312
61116  16.402004   88.009819  23.742513  ... -29.697613  25.963332  1.697312
16368  71.368202  128.389509 -40.860105  ... -29.697613  25.963332  1.697312
68705  56.232207  137.010944 -11.716995  ... -29.697613  25.963332  1.697312
17045  66.664387   81.860900 -31.245964  ... -29.697613  25.963332  1.697312
51873  23.823549   97.483777   0.322864  ... -29.697613  25.963332  1.697312
37701  44.929542   96.967099 -16.723351  ... -29.697613  25.963332  1.697312
39501  51.224641   64.629735 -73.829315  ... -29.697613  25.963332  1.697312
19802  19.986583  142.777156  39.264412  ... -29.697613  25.963332  1.697312
26622  39.853545  153.695099  -5.820128  ... -29.697613  25.963332  1.697312

[10 rows x 36 columns]

In [ ]:
model2 = Sequential()
model2.add(layers.Dense(120, activation=tf.nn.relu, input_shape=(36, )))
model2.add(layers.Dense(45, activation=tf.nn.relu))
model2.add(layers.Dense(32, activation=tf.nn.relu))
model2.add(layers.Dense(60, activation=tf.nn.softmax))

model2.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_25 (Dense)             (None, 120)               4440
_________________________________________________________________
dense_26 (Dense)             (None, 45)                5445
_________________________________________________________________
dense_27 (Dense)             (None, 32)                1472
_________________________________________________________________
dense_28 (Dense)             (None, 60)                1980
=================================================================
Total params: 13,337
Trainable params: 13,337
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model2.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
history = model2.fit_generator((df_n,df_y),
                    steps_per_epoch = 45, 
                    epochs=15)

Epoch 1/15
54666/54666 [==============================] - 3s 64us/step - loss: 1.2622 - acc: 0.5023
Epoch 2/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.7946 - acc: 0.7068
Epoch 3/15
54666/54666 [==============================] - 3s 57us/step - loss: 0.6175 - acc: 0.7748
Epoch 4/15
54666/54666 [==============================] - 3s 55us/step - loss: 0.5261 - acc: 0.8074
Epoch 5/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.4602 - acc: 0.8339
Epoch 6/15
54666/54666 [==============================] - 3s 55us/step - loss: 0.4082 - acc: 0.8587
Epoch 7/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.3694 - acc: 0.8759
Epoch 8/15
54666/54666 [==============================] - 3s 57us/step - loss: 0.3336 - acc: 0.8884
Epoch 9/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.3124 - acc: 0.8961
Epoch 10/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.2838 - acc: 0.9081
Epoch 11/15
54666/54666 [==============================] - 3s 55us/step - loss: 0.2678 - acc: 0.9131
Epoch 12/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.2524 - acc: 0.9183
Epoch 13/15
54666/54666 [==============================] - 3s 56us/step - loss: 0.2443 - acc: 0.9202
Epoch 14/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.2348 - acc: 0.9258
Epoch 15/15
54666/54666 [==============================] - 3s 55us/step - loss: 0.2241 - acc: 0.9288

In [ ]:
df_n1 = pd.DataFrame(columns=['X0','Y0','Z0','X1','Y1','Z1','X2','Y2','Z2','X3','Y3','Z3','X4','Y4','Z4','X5','Y5','Z5',
                              'X6','Y6','Z6','X7','Y7','Z7','X8','Y8','Z8','X9','Y9','Z9','X10','Y10','Z10','X11','Y11','Z11'])
df_y1 = pd.DataFrame(columns=['Class'])

chunk_X = chunks_X(X)
for j in chunk_X:
  batch_x = next(chunk_X)
  for i in range(0,10):
    if(batch_x.shape == (45,36)):
      n = np.random.randint(1,45)
      m = np.random.randint(1,36)
    else:
      n = np.random.randint(1,350)
      m = np.random.randint(1,36)
  batch_x.iat[n,m] = batch_x.iat[n,m]+0.0356
  df_interpolated = batch_x
  df_n1 = pd.concat([df_n1,df_interpolated])


chunk_Y = chunks_Y(Y)
for i in chunk_Y:
  batch_y = next(chunk_Y)
  df_y1 = pd.concat([df_y1,batch_y])

In [ ]:
model3 = Sequential()
model3.add(layers.Dense(120, activation=tf.nn.relu, input_shape=(36, )))
model3.add(layers.Dense(45, activation=tf.nn.relu))
model3.add(layers.Dense(32, activation=tf.nn.relu))
model3.add(layers.Dense(60, activation=tf.nn.softmax))

model3.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_29 (Dense)             (None, 120)               4440
_________________________________________________________________
dense_30 (Dense)             (None, 45)                5445
_________________________________________________________________
dense_31 (Dense)             (None, 32)                1472
_________________________________________________________________
dense_32 (Dense)             (None, 60)                1980
=================================================================
Total params: 13,337
Trainable params: 13,337
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model3.compile(optimizer=tf.train.AdamOptimizer(), 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model3.fit_generator((df_n1,df_y1),
                    steps_per_epoch = 45, 
                    epochs=15)

Epoch 1/15
54666/54666 [==============================] - 3s 61us/step - loss: 0.3834 - acc: 0.8706
Epoch 2/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.3695 - acc: 0.8740
Epoch 3/15
54666/54666 [==============================] - 3s 59us/step - loss: 0.3350 - acc: 0.8858
Epoch 4/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.3142 - acc: 0.8943
Epoch 5/15
54666/54666 [==============================] - 3s 60us/step - loss: 0.3010 - acc: 0.8996
Epoch 6/15
54666/54666 [==============================] - 3s 59us/step - loss: 0.2854 - acc: 0.9053
Epoch 7/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.2788 - acc: 0.9075
Epoch 8/15
54666/54666 [==============================] - 3s 58us/step - loss: 0.2601 - acc: 0.9146
Epoch 9/15
54666/54666 [==============================] - 3s 61us/step - loss: 0.2583 - acc: 0.9150
Epoch 10/15
54666/54666 [==============================] - 3s 59us/step - loss: 0.2459 - acc: 0.9198
Epoch 11/15
54666/54666 [==============================] - 3s 59us/step - loss: 0.2314 - acc: 0.9258
Epoch 12/15
54666/54666 [==============================] - 3s 60us/step - loss: 0.2223 - acc: 0.9279
Epoch 13/15
54666/54666 [==============================] - 3s 60us/step - loss: 0.2145 - acc: 0.9304
Epoch 14/15
54666/54666 [==============================] - 3s 62us/step - loss: 0.2091 - acc: 0.9348
Epoch 15/15
54666/54666 [==============================] - 3s 60us/step - loss: 0.1965 - acc: 0.9375